sudo: false
dist: "trusty" # otherwise 'python3-pip' won't be available
language: python
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
python: 
  - "3.6"
before_install:
  - "pip3 install -r requirements.txt"
  - "npm install"
notifications:
    slack: surprisetech:j8bAuVBQphzqvvpkfZ2FDSXs
before_script:
  - "FLASK_APP=app.py flask run &"
script:
  - pytest
