sudo: false
dist: trusty
language: python
addons:
  apt:
    packages:
    - python3
    - python3-pip
python:
- '3.6'
before_install:
- pip3 install -r requirements.txt
- npm install
notifications:
  slack: surprisetech:j8bAuVBQphzqvvpkfZ2FDSXs
before_script:
- touch config.py
- FLASK_APP=app.py flask run &
script:
- pytest
env:
  global:
  - secure: b+DjG7YxQF1NHSH6dlEcpjZh097OSpb03WC4esr79NutaAMrVCZoqjRIx+pjyGuI+M18ZiDo6QIqgULDfOuEFDU0v5tBU0Ip5cLq5KJb6zwDZrsBimlg+rYc4Y5gTlXIQP9cuQ9sw2YB9PvZyENdS2TQhNbVOPAFtw0Gxb3KBx8gH9uoAeN4BiVHmyB8R1QKg28rDJ/YNhhp4R+TXgjW9uXHj4M8rHTbohjUEnZxFhvc9EnuwihAVh8qvkhOlmJtxfay2MeEuAuvi3ANsNVC3BIQJs/v3b1ELhhtNgif3LzbPglvLU8eG1xdsl+yvuT4HFhwrCBjl4/TgO1h6GDhHoCdw3SpM7+86W5g6EBQMrh4GKHRfU+PWmXM+2idcxPIyIoKlNHp6faa/4f1bJMLgobbxi6zi0s5WDoHzjWLG2khL5D3xSPoqM2he/yada4X0tVP3703JdS/y7bH/oqgRqC4JAp5lU5I05CFzeOzZK9NSl9mFAjrHJVJ65Uo3c18kyAZCZrLJqxGYvIi7zS5huCXb9JpMcSjtx7FnvgF94humkGIJPqzQfGrVBzke/3Fv2XEiZmyCrzPOSJCbIrBwPcdjj2rSOqx5DZtbMKS2A+2D7WSEFbkoTpJY1XKH4pwIEPxii3+zF5AlWcFrcpnv29LUDU1nYwCDPeXhTC+NS8=
  - secure: x5Cb0ydeG6b23OAhDZQoLaKkMCG8Syz4wbtYCSxO1ZodHvyAG0doBpToiC6lf/2CLcTEjfsysdH7MS4Ful2GDn4nned8oH6tFh+s6x/Oxvy6uizYHRZQzSmMUqRDB5hw/k/cMq4sFmVq7+qRMYFNSmG6BIyCtaE7GdVQz6vcb8hGaT3cbfS36sUMROSfGGaUEsZtWwndpuOcMfKZ/z0A4gyyafW4Nke8Il+sfFIYsUzhmCYRoC6pNxi4RLeKGRYat19bNYJi8NKPikwJi6w2e6P/yzg8JVDNTr+YjkcwS8B4TKCbq8czjQRC53wV3tosUUPorhwvtWf1KBeb8FRDMLWpEvp2MxP3GkyX2hWtWM6lL75hO5eUMltVrRv3e4z5hp1kED0Hd17uG/xer4rvXkE00MmLKuCPEseErQ3H4YDl1O5D/gzhQQRXFzlJ20DSu8oSu0CG+gtMVp8B6i2HY50XYSnyLZcb2tIJL9Kp0xybmCjXph+aCQOTzzCYGmDOhRpNi8GpHLo7+lwXXwxFNRapKCYadQBBbJ6hXUoq6WktNxRUat7720QkyTpRqoZncOCEuBnHrhi8QvtkcEOq4F7T6OJCF8HCPj5nJPIglRSK2tEIgnMx3KvRkLj43uBvDDTYGk9eZ96hRAK+A25thl6l79ek2sWGP6gZOTDX5Mo=
  - secure: po/Nu4+VKI2PWZtP1HOK4+bqiJWUpvuAxgs0dhsdo2ipvmjWv4nRftu2zHjc4u6gVqze06hJP2gvjoG2ROYa4plZz+zBgA0zMG7oMWOgY7cuYHmW5fGxYYxnxY7ggpd9rWv6hHa0j0ocDPNmT2B9bzBdvtDenXA8nFJbCgAXeItGmciOncltE/OPEV+KtwEm9ePH4dGaa1iQBrn2xFDyx/JKNF63jZzFh9eHlZiNEHj0P4DvyZ84GNX8haDtpaRt2KqXt1Gccl4l4l+U6eplsTXLGYiStdGr/puvbDK0BIRdve5sLfkSMwUCLiYHSjC0cEr2jaeUsFHmG2oyXIH1ND4I5TtMlMCKhZrZluaukkCODBqdmdTVAwTXVCAOfGG58ylS3wNzPQxlmqAc+bBXvFSJ+m9OHMw66hGsSzIaDh2OzHIH9LxJsAeCdSaVj1kE2hg4P1ZFJZCZewfXwXSh/KbqVFqTJVGBVWW90ydIVt3cSR8FSMyTSiaK0Q5zzyTuGAEnnKR9LZqQAf/AeutLYiwKIPDVhuqEsywHDRd8lL3r7zxs8FDuGl03IA6kH3NZYqhThCi/Ktr/fv3/3GjIL02YKl5F2yMdefosJZaKHJ+valqfSh69eSXUIrX9NP5Ur0L+/fWLuRKNooLOauLXtj65XDLFFmRwWuOCGgpFeaM=
