sudo: false
dist: "trusty" # otherwise 'python3-pip' won't be available
language: python
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
python: 
  - "3.6"
before_install:
  - "pip3 install -r requirements.txt"
notifications:
    slack: surprisetech:j8bAuVBQphzqvvpkfZ2FDSXs
script:
  - pytest
